export ZSH="$HOME/.oh-my-zsh.sh"

ZSH_THEME="robbyrussell"

plugins=(git)
source $ZSH/oh-my-zsh.sh

# ALIASES
alias tf=terraform
alias k=kubectl
alias kl="kubectl logs"
alias kgp="kubectl get pods"

alias python=python3
alias pip=pip3

alias gs="git status"
alias gad="git add *"
alias gc="git commit -m"
alias gpush="git push"
alias gpull="git pull"
